/**
 * 이모지 grid suggestion(`:` 트리거, RD-004, UI-012/UI-013)의 항목 하나.
 * `block-type-options.ts`의 `BlockTypeOption`과 같은 자리의 데이터 모듈이다
 * — `char`는 렌더할 유니코드 문자, `keywords`는 검색어다.
 */
export type EmojiOption = {
  id: string;
  char: string;
  label: string;
  keywords: readonly string[];
};

/**
 * 하드코딩 큐레이션 이모지 목록(신규 npm 의존성 미추가, roadmap.md
 * "Emoji picker 데이터 소스·트리거·컬럼 수" 결정). 전체 유니코드 이모지
 * (1800+, skin tone 변형·ZWJ 다중 인물 합성·국기 포함)가 아니라 자주 쓰는
 * 서브셋(564개)만 골라 리터럴로 박아 넣었다 — 런타임에 파싱하는
 * JSON이나 외부 패키지가 아니다. id/char/keywords는 emojilib
 * (https://github.com/muan/emojilib, MIT)의 공개 키워드 데이터에서 정확한
 * 유니코드 문자를 조회해 생성했다(직접 타이핑한 이모지 문자의 오타 위험을
 * 없애기 위함) — keywords는 그중 검색에 유용한 상위 5개만 남기고 ASCII
 * 이모티콘 표기(":)")·다어절 키워드는 뺐다.
 */
export const EMOJI_OPTIONS: readonly EmojiOption[] = [
  // --- Smileys & emotion ---
  {
    id: "grinning-face",
    char: "😀",
    label: "Grinning Face",
    keywords: ["face", "smile", "happy", "joy", "grin"],
  },
  {
    id: "grinning-face-with-big-eyes",
    char: "😃",
    label: "Grinning Face With Big Eyes",
    keywords: ["face", "happy", "joy", "haha", "smile"],
  },
  {
    id: "grinning-face-with-smiling-eyes",
    char: "😄",
    label: "Grinning Face With Smiling Eyes",
    keywords: ["face", "happy", "joy", "funny", "haha"],
  },
  {
    id: "beaming-face-with-smiling-eyes",
    char: "😁",
    label: "Beaming Face With Smiling Eyes",
    keywords: ["face", "happy", "smile", "joy", "kawaii"],
  },
  {
    id: "grinning-squinting-face",
    char: "😆",
    label: "Grinning Squinting Face",
    keywords: ["happy", "joy", "lol", "satisfied", "haha"],
  },
  {
    id: "grinning-face-with-sweat",
    char: "😅",
    label: "Grinning Face With Sweat",
    keywords: ["face", "hot", "happy", "laugh", "sweat"],
  },
  {
    id: "rolling-on-the-floor-laughing",
    char: "🤣",
    label: "Rolling On The Floor Laughing",
    keywords: ["face", "rolling", "floor", "laughing", "lol"],
  },
  {
    id: "face-with-tears-of-joy",
    char: "😂",
    label: "Face With Tears Of Joy",
    keywords: ["face", "cry", "tears", "weep", "happy"],
  },
  {
    id: "slightly-smiling-face",
    char: "🙂",
    label: "Slightly Smiling Face",
    keywords: ["face", "smile", "fine", "happy", "this"],
  },
  {
    id: "upside-down-face",
    char: "🙃",
    label: "Upside Down Face",
    keywords: ["face", "flipped", "silly", "smile", "sarcasm"],
  },
  {
    id: "melting-face",
    char: "🫠",
    label: "Melting Face",
    keywords: ["hot", "heat", "disappear", "dissolve", "dread"],
  },
  {
    id: "winking-face",
    char: "😉",
    label: "Winking Face",
    keywords: ["face", "happy", "mischievous", "secret", "smile"],
  },
  {
    id: "smiling-face-with-smiling-eyes",
    char: "😊",
    label: "Smiling Face With Smiling Eyes",
    keywords: ["face", "smile", "happy", "flushed", "crush"],
  },
  {
    id: "smiling-face-with-halo",
    char: "😇",
    label: "Smiling Face With Halo",
    keywords: ["face", "angel", "heaven", "halo", "innocent"],
  },
  {
    id: "smiling-face-with-hearts",
    char: "🥰",
    label: "Smiling Face With Hearts",
    keywords: ["face", "love", "like", "affection", "valentines"],
  },
  {
    id: "smiling-face-with-heart-eyes",
    char: "😍",
    label: "Smiling Face With Heart Eyes",
    keywords: ["face", "love", "like", "affection", "valentines"],
  },
  {
    id: "star-struck",
    char: "🤩",
    label: "Star Struck",
    keywords: ["face", "smile", "starry", "eyes", "grinning"],
  },
  {
    id: "face-blowing-a-kiss",
    char: "😘",
    label: "Face Blowing A Kiss",
    keywords: ["face", "love", "like", "affection", "valentines"],
  },
  {
    id: "kissing-face",
    char: "😗",
    label: "Kissing Face",
    keywords: ["love", "like", "face", "3", "valentines"],
  },
  {
    id: "smiling-face",
    char: "☺️",
    label: "Smiling Face",
    keywords: ["face", "blush", "massage", "happiness", "happy"],
  },
  {
    id: "kissing-face-with-closed-eyes",
    char: "😚",
    label: "Kissing Face With Closed Eyes",
    keywords: ["face", "love", "like", "affection", "valentines"],
  },
  {
    id: "kissing-face-with-smiling-eyes",
    char: "😙",
    label: "Kissing Face With Smiling Eyes",
    keywords: ["face", "affection", "valentines", "infatuation", "kiss"],
  },
  {
    id: "smiling-face-with-tear",
    char: "🥲",
    label: "Smiling Face With Tear",
    keywords: ["sad", "cry", "pretend", "grateful", "happy"],
  },
  {
    id: "face-savoring-food",
    char: "😋",
    label: "Face Savoring Food",
    keywords: ["happy", "joy", "tongue", "smile", "face"],
  },
  {
    id: "face-with-tongue",
    char: "😛",
    label: "Face With Tongue",
    keywords: ["face", "prank", "childish", "playful", "mischievous"],
  },
  {
    id: "winking-face-with-tongue",
    char: "😜",
    label: "Winking Face With Tongue",
    keywords: ["face", "prank", "childish", "playful", "mischievous"],
  },
  {
    id: "zany-face",
    char: "🤪",
    label: "Zany Face",
    keywords: ["face", "goofy", "crazy", "excited", "eye"],
  },
  {
    id: "squinting-face-with-tongue",
    char: "😝",
    label: "Squinting Face With Tongue",
    keywords: ["face", "prank", "playful", "mischievous", "smile"],
  },
  {
    id: "money-mouth-face",
    char: "🤑",
    label: "Money Mouth Face",
    keywords: ["face", "rich", "dollar", "money", "eyes"],
  },
  {
    id: "hugging-face",
    char: "🤗",
    label: "Hugging Face",
    keywords: ["face", "smile", "hug", "hands", "hugs"],
  },
  {
    id: "saluting-face",
    char: "🫡",
    label: "Saluting Face",
    keywords: ["respect", "salute", "ok", "sunny", "troops"],
  },
  {
    id: "shushing-face",
    char: "🤫",
    label: "Shushing Face",
    keywords: ["face", "quiet", "shhh", "closed", "covering"],
  },
  {
    id: "thinking-face",
    char: "🤔",
    label: "Thinking Face",
    keywords: ["face", "hmmm", "think", "consider", "chin"],
  },
  {
    id: "face-with-hand-over-mouth",
    char: "🤭",
    label: "Face With Hand Over Mouth",
    keywords: ["face", "whoops", "shock", "surprise", "blushing"],
  },
  {
    id: "neutral-face",
    char: "😐",
    label: "Neutral Face",
    keywords: ["indifference", "meh", "neutral", "deadpan", "faced"],
  },
  {
    id: "expressionless-face",
    char: "😑",
    label: "Expressionless Face",
    keywords: ["face", "indifferent", "-_-", "meh", "deadpan"],
  },
  {
    id: "face-with-rolling-eyes",
    char: "🙄",
    label: "Face With Rolling Eyes",
    keywords: ["face", "eyeroll", "frustrated", "eye", "roll"],
  },
  {
    id: "smirking-face",
    char: "😏",
    label: "Smirking Face",
    keywords: ["face", "smile", "mean", "prank", "smug"],
  },
  {
    id: "persevering-face",
    char: "😣",
    label: "Persevering Face",
    keywords: ["face", "sick", "no", "upset", "oops"],
  },
  {
    id: "disappointed-face",
    char: "😞",
    label: "Disappointed Face",
    keywords: ["face", "sad", "upset", "depressed", "sadface"],
  },
  {
    id: "downcast-face-with-sweat",
    char: "😓",
    label: "Downcast Face With Sweat",
    keywords: ["face", "hot", "sad", "tired", "exercise"],
  },
  {
    id: "weary-face",
    char: "😩",
    label: "Weary Face",
    keywords: ["face", "tired", "sleepy", "sad", "frustrated"],
  },
  {
    id: "tired-face",
    char: "😫",
    label: "Tired Face",
    keywords: ["sick", "whine", "upset", "frustrated", "distraught"],
  },
  {
    id: "yawning-face",
    char: "🥱",
    label: "Yawning Face",
    keywords: ["tired", "sleepy", "bored", "yawn"],
  },
  {
    id: "face-with-steam-from-nose",
    char: "😤",
    label: "Face With Steam From Nose",
    keywords: ["face", "gas", "phew", "proud", "pride"],
  },
  {
    id: "pouting-face",
    char: "😡",
    label: "Pouting Face",
    keywords: ["angry", "mad", "hate", "despise", "enraged"],
  },
  {
    id: "angry-face",
    char: "😠",
    label: "Angry Face",
    keywords: ["mad", "face", "annoyed", "frustrated", "anger"],
  },
  {
    id: "face-with-symbols-on-mouth",
    char: "🤬",
    label: "Face With Symbols On Mouth",
    keywords: ["face", "swearing", "cursing", "cussing", "profanity"],
  },
  {
    id: "exploding-head",
    char: "🤯",
    label: "Exploding Head",
    keywords: ["face", "shocked", "mind", "blown", "blowing"],
  },
  {
    id: "flushed-face",
    char: "😳",
    label: "Flushed Face",
    keywords: ["face", "blush", "shy", "flattered", "blushing"],
  },
  {
    id: "hot-face",
    char: "🥵",
    label: "Hot Face",
    keywords: ["face", "feverish", "heat", "red", "sweating"],
  },
  {
    id: "cold-face",
    char: "🥶",
    label: "Cold Face",
    keywords: ["face", "blue", "freezing", "frozen", "frostbite"],
  },
  {
    id: "woozy-face",
    char: "🥴",
    label: "Woozy Face",
    keywords: ["face", "dizzy", "intoxicated", "tipsy", "wavy"],
  },
  {
    id: "dizzy-face",
    char: "😵",
    label: "Dizzy Face",
    keywords: ["spent", "unconscious", "xox", "dizzy", "cross"],
  },
  {
    id: "nauseated-face",
    char: "🤢",
    label: "Nauseated Face",
    keywords: ["face", "vomit", "gross", "green", "sick"],
  },
  {
    id: "sneezing-face",
    char: "🤧",
    label: "Sneezing Face",
    keywords: ["face", "gesundheit", "sneeze", "sick", "allergy"],
  },
  {
    id: "sleepy-face",
    char: "😪",
    label: "Sleepy Face",
    keywords: ["face", "tired", "rest", "nap", "bubble"],
  },
  {
    id: "sleeping-face",
    char: "😴",
    label: "Sleeping Face",
    keywords: ["face", "tired", "sleepy", "night", "zzz"],
  },
  {
    id: "relieved-face",
    char: "😌",
    label: "Relieved Face",
    keywords: ["face", "relaxed", "phew", "massage", "happiness"],
  },
  {
    id: "pensive-face",
    char: "😔",
    label: "Pensive Face",
    keywords: ["face", "sad", "depressed", "upset", "dejected"],
  },
  {
    id: "confused-face",
    char: "😕",
    label: "Confused Face",
    keywords: ["face", "indifference", "huh", "weird", "hmmm"],
  },
  {
    id: "slightly-frowning-face",
    char: "🙁",
    label: "Slightly Frowning Face",
    keywords: ["face", "frowning", "disappointed", "sad", "upset"],
  },
  {
    id: "frowning-face",
    char: "☹️",
    label: "Frowning Face",
    keywords: ["face", "sad", "upset", "frown", "megafrown"],
  },
  {
    id: "worried-face",
    char: "😟",
    label: "Worried Face",
    keywords: ["face", "concern", "nervous", "sad", "sadface"],
  },
  {
    id: "crying-face",
    char: "😢",
    label: "Crying Face",
    keywords: ["face", "tears", "sad", "depressed", "upset"],
  },
  {
    id: "loudly-crying-face",
    char: "😭",
    label: "Loudly Crying Face",
    keywords: ["sobbing", "face", "cry", "tears", "sad"],
  },
  {
    id: "face-screaming-in-fear",
    char: "😱",
    label: "Face Screaming In Fear",
    keywords: ["face", "munch", "scared", "omg", "alone"],
  },
  {
    id: "fearful-face",
    char: "😨",
    label: "Fearful Face",
    keywords: ["face", "scared", "terrified", "nervous", "fear"],
  },
  {
    id: "anxious-face-with-sweat",
    char: "😰",
    label: "Anxious Face With Sweat",
    keywords: ["face", "nervous", "sweat", "blue", "cold"],
  },
  {
    id: "astonished-face",
    char: "😲",
    label: "Astonished Face",
    keywords: ["face", "xox", "surprised", "poisoned", "amazed"],
  },
  {
    id: "pleading-face",
    char: "🥺",
    label: "Pleading Face",
    keywords: ["face", "begging", "mercy", "cry", "tears"],
  },
  {
    id: "grimacing-face",
    char: "😬",
    label: "Grimacing Face",
    keywords: ["face", "grimace", "teeth", "awkward", "eek"],
  },
  {
    id: "anguished-face",
    char: "😧",
    label: "Anguished Face",
    keywords: ["face", "stunned", "nervous", "pained"],
  },
  {
    id: "partying-face",
    char: "🥳",
    label: "Partying Face",
    keywords: ["face", "celebration", "woohoo", "birthday", "hat"],
  },
  {
    id: "smiling-face-with-sunglasses",
    char: "😎",
    label: "Smiling Face With Sunglasses",
    keywords: ["face", "cool", "smile", "summer", "beach"],
  },
  {
    id: "nerd-face",
    char: "🤓",
    label: "Nerd Face",
    keywords: ["face", "nerdy", "geek", "dork", "glasses"],
  },
  {
    id: "face-with-monocle",
    char: "🧐",
    label: "Face With Monocle",
    keywords: ["face", "stuffy", "wealthy", "rich", "exploration"],
  },
  {
    id: "confounded-face",
    char: "😖",
    label: "Confounded Face",
    keywords: ["face", "confused", "sick", "unwell", "oops"],
  },
  {
    id: "sad-but-relieved-face",
    char: "😥",
    label: "Sad But Relieved Face",
    keywords: ["face", "phew", "sweat", "nervous", "disappointed"],
  },
  {
    id: "unamused-face",
    char: "😒",
    label: "Unamused Face",
    keywords: ["indifference", "bored", "serious", "sarcasm", "unimpressed"],
  },
  {
    id: "drooling-face",
    char: "🤤",
    label: "Drooling Face",
    keywords: ["face", "drool"],
  },
  {
    id: "lying-face",
    char: "🤥",
    label: "Lying Face",
    keywords: ["face", "lie", "pinocchio", "liar", "long"],
  },
  {
    id: "face-vomiting",
    char: "🤮",
    label: "Face Vomiting",
    keywords: ["face", "sick", "barf", "ill", "mouth"],
  },
  {
    id: "face-with-diagonal-mouth",
    char: "🫤",
    label: "Face With Diagonal Mouth",
    keywords: ["skeptic", "confuse", "frustrated", "indifferent", "confused"],
  },
  {
    id: "dotted-line-face",
    char: "🫥",
    label: "Dotted Line Face",
    keywords: ["invisible", "lonely", "isolation", "depression", "depressed"],
  },
  {
    id: "zipper-mouth-face",
    char: "🤐",
    label: "Zipper Mouth Face",
    keywords: ["face", "sealed", "zipper", "secret", "hush"],
  },
  {
    id: "face-with-raised-eyebrow",
    char: "🤨",
    label: "Face With Raised Eyebrow",
    keywords: ["face", "distrust", "scepticism", "disapproval", "disbelief"],
  },
  {
    id: "skull",
    char: "💀",
    label: "Skull",
    keywords: ["dead", "skeleton", "creepy", "death", "body"],
  },
  {
    id: "skull-and-crossbones",
    char: "☠️",
    label: "Skull And Crossbones",
    keywords: ["poison", "danger", "deadly", "scary", "death"],
  },
  {
    id: "clown-face",
    char: "🤡",
    label: "Clown Face",
    keywords: ["face", "mock"],
  },
  {
    id: "ogre",
    char: "👹",
    label: "Ogre",
    keywords: ["monster", "red", "mask", "halloween", "scary"],
  },
  {
    id: "goblin",
    char: "👺",
    label: "Goblin",
    keywords: ["red", "evil", "mask", "monster", "scary"],
  },
  {
    id: "ghost",
    char: "👻",
    label: "Ghost",
    keywords: ["halloween", "spooky", "scary", "creature", "disappear"],
  },
  {
    id: "alien",
    char: "👽",
    label: "Alien",
    keywords: ["ufo", "paul", "weird", "outer_space", "creature"],
  },
  {
    id: "alien-monster",
    char: "👾",
    label: "Alien Monster",
    keywords: ["game", "arcade", "play", "creature", "extraterrestrial"],
  },
  {
    id: "robot",
    char: "🤖",
    label: "Robot",
    keywords: ["computer", "machine", "bot", "face", "monster"],
  },
  {
    id: "pile-of-poo",
    char: "💩",
    label: "Pile Of Poo",
    keywords: ["hankey", "shitface", "fail", "turd", "shit"],
  },
  // --- Hearts & love ---
  {
    id: "red-heart",
    char: "❤️",
    label: "Red Heart",
    keywords: ["love", "like", "valentines", "black", "heavy"],
  },
  {
    id: "orange-heart",
    char: "🧡",
    label: "Orange Heart",
    keywords: ["love", "like", "affection", "valentines"],
  },
  {
    id: "yellow-heart",
    char: "💛",
    label: "Yellow Heart",
    keywords: ["love", "like", "affection", "valentines", "bf"],
  },
  {
    id: "green-heart",
    char: "💚",
    label: "Green Heart",
    keywords: ["love", "like", "affection", "valentines", "nct"],
  },
  {
    id: "blue-heart",
    char: "💙",
    label: "Blue Heart",
    keywords: ["love", "like", "affection", "valentines", "brand"],
  },
  {
    id: "purple-heart",
    char: "💜",
    label: "Purple Heart",
    keywords: ["love", "like", "affection", "valentines", "bts"],
  },
  {
    id: "black-heart",
    char: "🖤",
    label: "Black Heart",
    keywords: ["evil", "dark", "wicked"],
  },
  { id: "white-heart", char: "🤍", label: "White Heart", keywords: ["pure"] },
  { id: "brown-heart", char: "🤎", label: "Brown Heart", keywords: ["coffee"] },
  {
    id: "broken-heart",
    char: "💔",
    label: "Broken Heart",
    keywords: ["sad", "sorry", "break", "heart", "heartbreak"],
  },
  {
    id: "heart-exclamation",
    char: "❣️",
    label: "Heart Exclamation",
    keywords: ["decoration", "love", "above", "an", "as"],
  },
  {
    id: "two-hearts",
    char: "💕",
    label: "Two Hearts",
    keywords: ["love", "like", "affection", "valentines", "heart"],
  },
  {
    id: "revolving-hearts",
    char: "💞",
    label: "Revolving Hearts",
    keywords: ["love", "like", "affection", "valentines", "heart"],
  },
  {
    id: "beating-heart",
    char: "💓",
    label: "Beating Heart",
    keywords: ["love", "like", "affection", "valentines", "pink"],
  },
  {
    id: "growing-heart",
    char: "💗",
    label: "Growing Heart",
    keywords: ["like", "love", "affection", "valentines", "pink"],
  },
  {
    id: "sparkling-heart",
    char: "💖",
    label: "Sparkling Heart",
    keywords: ["love", "like", "affection", "valentines", "excited"],
  },
  {
    id: "heart-with-arrow",
    char: "💘",
    label: "Heart With Arrow",
    keywords: ["love", "like", "heart", "affection", "valentines"],
  },
  {
    id: "heart-with-ribbon",
    char: "💝",
    label: "Heart With Ribbon",
    keywords: ["love", "valentines", "box", "chocolate", "chocolates"],
  },
  {
    id: "heart-decoration",
    char: "💟",
    label: "Heart Decoration",
    keywords: ["purple-square", "love", "like"],
  },
  {
    id: "kiss-mark",
    char: "💋",
    label: "Kiss Mark",
    keywords: ["face", "lips", "love", "like", "affection"],
  },
  {
    id: "hundred-points",
    char: "💯",
    label: "Hundred Points",
    keywords: ["score", "perfect", "numbers", "century", "exam"],
  },
  // --- People & body(제스처, skin tone 변형 제외) ---
  {
    id: "waving-hand",
    char: "👋",
    label: "Waving Hand",
    keywords: ["wave", "hands", "gesture", "goodbye", "solong"],
  },
  {
    id: "raised-back-of-hand",
    char: "🤚",
    label: "Raised Back Of Hand",
    keywords: ["fingers", "raised", "backhand", "body"],
  },
  {
    id: "hand-with-fingers-splayed",
    char: "🖐️",
    label: "Hand With Fingers Splayed",
    keywords: ["hand", "fingers", "palm", "body", "finger"],
  },
  {
    id: "raised-hand",
    char: "✋",
    label: "Raised Hand",
    keywords: ["fingers", "stop", "highfive", "palm", "ban"],
  },
  {
    id: "vulcan-salute",
    char: "🖖",
    label: "Vulcan Salute",
    keywords: ["hand", "fingers", "spock", "between", "body"],
  },
  {
    id: "ok-hand",
    char: "👌",
    label: "Ok Hand",
    keywords: ["fingers", "limbs", "perfect", "ok", "okay"],
  },
  {
    id: "pinched-fingers",
    char: "🤌",
    label: "Pinched Fingers",
    keywords: ["size", "tiny", "small", "che", "finger"],
  },
  {
    id: "pinching-hand",
    char: "🤏",
    label: "Pinching Hand",
    keywords: ["tiny", "small", "size", "amount", "body"],
  },
  {
    id: "victory-hand",
    char: "✌️",
    label: "Victory Hand",
    keywords: ["fingers", "ohyeah", "hand", "peace", "victory"],
  },
  {
    id: "crossed-fingers",
    char: "🤞",
    label: "Crossed Fingers",
    keywords: ["good", "lucky", "body", "cross", "finger"],
  },
  {
    id: "love-you-gesture",
    char: "🤟",
    label: "Love You Gesture",
    keywords: ["hand", "fingers", "gesture", "body", "i"],
  },
  {
    id: "sign-of-the-horns",
    char: "🤘",
    label: "Sign Of The Horns",
    keywords: ["hand", "fingers", "evil_eye", "sign_of_horns", "rock_on"],
  },
  {
    id: "call-me-hand",
    char: "🤙",
    label: "Call Me Hand",
    keywords: ["hands", "gesture", "shaka", "body", "phone"],
  },
  {
    id: "backhand-index-pointing-left",
    char: "👈",
    label: "Backhand Index Pointing Left",
    keywords: ["direction", "fingers", "hand", "left", "body"],
  },
  {
    id: "backhand-index-pointing-right",
    char: "👉",
    label: "Backhand Index Pointing Right",
    keywords: ["fingers", "hand", "direction", "right", "body"],
  },
  {
    id: "backhand-index-pointing-up",
    char: "👆",
    label: "Backhand Index Pointing Up",
    keywords: ["fingers", "hand", "direction", "up", "body"],
  },
  {
    id: "middle-finger",
    char: "🖕",
    label: "Middle Finger",
    keywords: ["hand", "fingers", "rude", "middle", "flipping"],
  },
  {
    id: "backhand-index-pointing-down",
    char: "👇",
    label: "Backhand Index Pointing Down",
    keywords: ["fingers", "hand", "direction", "down", "body"],
  },
  {
    id: "index-pointing-up",
    char: "☝️",
    label: "Index Pointing Up",
    keywords: ["hand", "fingers", "direction", "up", "body"],
  },
  {
    id: "thumbs-up",
    char: "👍",
    label: "Thumbs Up",
    keywords: ["thumbsup", "yes", "awesome", "good", "agree"],
  },
  {
    id: "thumbs-down",
    char: "👎",
    label: "Thumbs Down",
    keywords: ["thumbsdown", "no", "dislike", "hand", "-1"],
  },
  {
    id: "raised-fist",
    char: "✊",
    label: "Raised Fist",
    keywords: ["fingers", "hand", "grasp", "body", "clenched"],
  },
  {
    id: "oncoming-fist",
    char: "👊",
    label: "Oncoming Fist",
    keywords: ["angry", "violence", "fist", "hit", "attack"],
  },
  {
    id: "clapping-hands",
    char: "👏",
    label: "Clapping Hands",
    keywords: ["hands", "praise", "applause", "congrats", "yay"],
  },
  {
    id: "raising-hands",
    char: "🙌",
    label: "Raising Hands",
    keywords: ["gesture", "hooray", "yea", "celebration", "hands"],
  },
  {
    id: "open-hands",
    char: "👐",
    label: "Open Hands",
    keywords: ["fingers", "butterfly", "hands", "open", "body"],
  },
  {
    id: "palms-up-together",
    char: "🤲",
    label: "Palms Up Together",
    keywords: ["hands", "gesture", "cupped", "prayer", "body"],
  },
  {
    id: "handshake",
    char: "🤝",
    label: "Handshake",
    keywords: ["agreement", "shake", "deal", "hand", "hands"],
  },
  {
    id: "folded-hands",
    char: "🙏",
    label: "Folded Hands",
    keywords: ["please", "hope", "wish", "namaste", "highfive"],
  },
  {
    id: "writing-hand",
    char: "✍️",
    label: "Writing Hand",
    keywords: [
      "lower_left_ballpoint_pen",
      "stationery",
      "write",
      "compose",
      "body",
    ],
  },
  {
    id: "flexed-biceps",
    char: "💪",
    label: "Flexed Biceps",
    keywords: ["arm", "flex", "hand", "summer", "strong"],
  },
  {
    id: "eyes",
    char: "👀",
    label: "Eyes",
    keywords: ["look", "watch", "stalk", "peek", "see"],
  },
  {
    id: "eye",
    char: "👁️",
    label: "Eye",
    keywords: ["face", "look", "see", "watch", "stare"],
  },
  {
    id: "ear",
    char: "👂",
    label: "Ear",
    keywords: ["face", "hear", "sound", "listen", "body"],
  },
  {
    id: "nose",
    char: "👃",
    label: "Nose",
    keywords: ["smell", "sniff", "body", "smelling", "sniffing"],
  },
  {
    id: "brain",
    char: "🧠",
    label: "Brain",
    keywords: ["smart", "intelligent", "body", "organ"],
  },
  {
    id: "tooth",
    char: "🦷",
    label: "Tooth",
    keywords: ["teeth", "dentist", "body"],
  },
  { id: "bone", char: "🦴", label: "Bone", keywords: ["skeleton", "body"] },
  {
    id: "tongue",
    char: "👅",
    label: "Tongue",
    keywords: ["mouth", "playful", "body", "out", "taste"],
  },
  {
    id: "mouth",
    char: "👄",
    label: "Mouth",
    keywords: ["kiss", "body", "kissing", "lips"],
  },
  {
    id: "baby",
    char: "👶",
    label: "Baby",
    keywords: ["child", "boy", "girl", "toddler", "newborn"],
  },
  {
    id: "footprints",
    char: "👣",
    label: "Footprints",
    keywords: ["feet", "tracking", "walking", "beach", "body"],
  },
  // --- Animals & nature ---
  {
    id: "dog-face",
    char: "🐶",
    label: "Dog Face",
    keywords: ["animal", "friend", "nature", "woof", "puppy"],
  },
  {
    id: "cat-face",
    char: "🐱",
    label: "Cat Face",
    keywords: ["animal", "meow", "nature", "pet", "kitten"],
  },
  {
    id: "mouse-face",
    char: "🐭",
    label: "Mouse Face",
    keywords: ["animal", "nature", "cheese_wedge", "rodent"],
  },
  {
    id: "hamster",
    char: "🐹",
    label: "Hamster",
    keywords: ["animal", "nature", "face", "pet"],
  },
  {
    id: "rabbit-face",
    char: "🐰",
    label: "Rabbit Face",
    keywords: ["animal", "nature", "pet", "spring", "magic"],
  },
  {
    id: "fox",
    char: "🦊",
    label: "Fox",
    keywords: ["animal", "nature", "face"],
  },
  {
    id: "bear",
    char: "🐻",
    label: "Bear",
    keywords: ["animal", "nature", "wild", "face", "teddy"],
  },
  {
    id: "panda",
    char: "🐼",
    label: "Panda",
    keywords: ["animal", "nature", "face"],
  },
  {
    id: "koala",
    char: "🐨",
    label: "Koala",
    keywords: ["animal", "nature", "bear", "face", "marsupial"],
  },
  {
    id: "tiger-face",
    char: "🐯",
    label: "Tiger Face",
    keywords: ["animal", "cat", "danger", "wild", "nature"],
  },
  {
    id: "lion",
    char: "🦁",
    label: "Lion",
    keywords: ["animal", "nature", "face", "leo", "zodiac"],
  },
  {
    id: "cow-face",
    char: "🐮",
    label: "Cow Face",
    keywords: ["beef", "ox", "animal", "nature", "moo"],
  },
  {
    id: "pig-face",
    char: "🐷",
    label: "Pig Face",
    keywords: ["animal", "oink", "nature", "head"],
  },
  {
    id: "frog",
    char: "🐸",
    label: "Frog",
    keywords: ["animal", "nature", "croak", "toad", "face"],
  },
  {
    id: "monkey-face",
    char: "🐵",
    label: "Monkey Face",
    keywords: ["animal", "nature", "circus", "head"],
  },
  {
    id: "see-no-evil-monkey",
    char: "🙈",
    label: "See No Evil Monkey",
    keywords: ["monkey", "animal", "nature", "haha", "blind"],
  },
  {
    id: "hear-no-evil-monkey",
    char: "🙉",
    label: "Hear No Evil Monkey",
    keywords: ["animal", "monkey", "nature", "covering", "deaf"],
  },
  {
    id: "speak-no-evil-monkey",
    char: "🙊",
    label: "Speak No Evil Monkey",
    keywords: ["monkey", "animal", "nature", "omg", "covering"],
  },
  {
    id: "chicken",
    char: "🐔",
    label: "Chicken",
    keywords: ["animal", "cluck", "nature", "bird", "hen"],
  },
  {
    id: "penguin",
    char: "🐧",
    label: "Penguin",
    keywords: ["animal", "nature", "bird"],
  },
  {
    id: "bird",
    char: "🐦",
    label: "Bird",
    keywords: ["animal", "nature", "fly", "tweet", "spring"],
  },
  {
    id: "duck",
    char: "🦆",
    label: "Duck",
    keywords: ["animal", "nature", "bird", "mallard"],
  },
  {
    id: "eagle",
    char: "🦅",
    label: "Eagle",
    keywords: ["animal", "nature", "bird", "bald"],
  },
  {
    id: "owl",
    char: "🦉",
    label: "Owl",
    keywords: ["animal", "nature", "bird", "hoot", "wise"],
  },
  {
    id: "bat",
    char: "🦇",
    label: "Bat",
    keywords: ["animal", "nature", "blind", "vampire", "batman"],
  },
  {
    id: "wolf",
    char: "🐺",
    label: "Wolf",
    keywords: ["animal", "nature", "wild", "face"],
  },
  {
    id: "horse-face",
    char: "🐴",
    label: "Horse Face",
    keywords: ["animal", "brown", "nature", "head"],
  },
  {
    id: "unicorn",
    char: "🦄",
    label: "Unicorn",
    keywords: ["animal", "nature", "mystical", "face"],
  },
  {
    id: "honeybee",
    char: "🐝",
    label: "Honeybee",
    keywords: ["animal", "insect", "nature", "bug", "spring"],
  },
  {
    id: "butterfly",
    char: "🦋",
    label: "Butterfly",
    keywords: ["animal", "insect", "nature", "caterpillar", "pretty"],
  },
  {
    id: "snail",
    char: "🐌",
    label: "Snail",
    keywords: ["slow", "animal", "shell", "garden", "slug"],
  },
  {
    id: "lady-beetle",
    char: "🐞",
    label: "Lady Beetle",
    keywords: ["animal", "insect", "nature", "ladybug", "bug"],
  },
  {
    id: "spider",
    char: "🕷️",
    label: "Spider",
    keywords: ["animal", "arachnid", "insect"],
  },
  {
    id: "turtle",
    char: "🐢",
    label: "Turtle",
    keywords: ["animal", "slow", "nature", "tortoise", "terrapin"],
  },
  {
    id: "snake",
    char: "🐍",
    label: "Snake",
    keywords: ["animal", "evil", "nature", "hiss", "python"],
  },
  {
    id: "dragon",
    char: "🐉",
    label: "Dragon",
    keywords: ["animal", "myth", "nature", "chinese", "green"],
  },
  {
    id: "dragon-face",
    char: "🐲",
    label: "Dragon Face",
    keywords: ["animal", "myth", "nature", "chinese", "green"],
  },
  {
    id: "octopus",
    char: "🐙",
    label: "Octopus",
    keywords: ["animal", "creature", "ocean", "sea", "nature"],
  },
  {
    id: "shark",
    char: "🦈",
    label: "Shark",
    keywords: ["animal", "nature", "fish", "sea", "ocean"],
  },
  {
    id: "dolphin",
    char: "🐬",
    label: "Dolphin",
    keywords: ["animal", "nature", "fish", "sea", "ocean"],
  },
  {
    id: "whale",
    char: "🐋",
    label: "Whale",
    keywords: ["animal", "nature", "sea", "ocean", "whale2"],
  },
  {
    id: "fish",
    char: "🐟",
    label: "Fish",
    keywords: ["animal", "food", "nature", "freshwater", "pisces"],
  },
  {
    id: "crocodile",
    char: "🐊",
    label: "Crocodile",
    keywords: ["animal", "nature", "reptile", "lizard", "alligator"],
  },
  {
    id: "elephant",
    char: "🐘",
    label: "Elephant",
    keywords: ["animal", "nature", "nose", "th", "circus"],
  },
  {
    id: "camel",
    char: "🐪",
    label: "Camel",
    keywords: ["animal", "hot", "desert", "hump", "arabian"],
  },
  {
    id: "giraffe",
    char: "🦒",
    label: "Giraffe",
    keywords: ["animal", "nature", "spots", "safari", "face"],
  },
  {
    id: "rhinoceros",
    char: "🦏",
    label: "Rhinoceros",
    keywords: ["animal", "nature", "horn", "rhino"],
  },
  {
    id: "kangaroo",
    char: "🦘",
    label: "Kangaroo",
    keywords: ["animal", "nature", "australia", "joey", "hop"],
  },
  {
    id: "paw-prints",
    char: "🐾",
    label: "Paw Prints",
    keywords: ["animal", "tracking", "footprints", "dog", "cat"],
  },
  {
    id: "rooster",
    char: "🐓",
    label: "Rooster",
    keywords: ["animal", "nature", "chicken", "bird", "cock"],
  },
  {
    id: "peacock",
    char: "🦚",
    label: "Peacock",
    keywords: ["animal", "nature", "peahen", "bird", "ostentatious"],
  },
  {
    id: "parrot",
    char: "🦜",
    label: "Parrot",
    keywords: ["animal", "nature", "bird", "pirate", "talk"],
  },
  {
    id: "swan",
    char: "🦢",
    label: "Swan",
    keywords: ["animal", "nature", "bird", "cygnet", "duckling"],
  },
  {
    id: "flamingo",
    char: "🦩",
    label: "Flamingo",
    keywords: ["animal", "flamboyant", "tropical"],
  },
  {
    id: "sloth",
    char: "🦥",
    label: "Sloth",
    keywords: ["animal", "lazy", "slow"],
  },
  {
    id: "otter",
    char: "🦦",
    label: "Otter",
    keywords: ["animal", "fishing", "playful"],
  },
  {
    id: "skunk",
    char: "🦨",
    label: "Skunk",
    keywords: ["animal", "smelly", "stink"],
  },
  {
    id: "hedgehog",
    char: "🦔",
    label: "Hedgehog",
    keywords: ["animal", "nature", "spiny", "face"],
  },
  // --- Nature, plants & weather ---
  {
    id: "sun",
    char: "☀️",
    label: "Sun",
    keywords: ["weather", "nature", "brightness", "summer", "beach"],
  },
  {
    id: "sun-behind-small-cloud",
    char: "🌤️",
    label: "Sun Behind Small Cloud",
    keywords: ["weather", "white"],
  },
  {
    id: "cloud",
    char: "☁️",
    label: "Cloud",
    keywords: ["weather", "sky", "cloudy", "overcast"],
  },
  {
    id: "sun-behind-rain-cloud",
    char: "🌦️",
    label: "Sun Behind Rain Cloud",
    keywords: ["weather", "white"],
  },
  {
    id: "cloud-with-lightning-and-rain",
    char: "⛈️",
    label: "Cloud With Lightning And Rain",
    keywords: ["weather", "lightning", "thunder"],
  },
  {
    id: "high-voltage",
    char: "⚡",
    label: "High Voltage",
    keywords: ["thunder", "weather", "fast", "zap", "danger"],
  },
  {
    id: "snowflake",
    char: "❄️",
    label: "Snowflake",
    keywords: ["winter", "season", "cold", "weather", "christmas"],
  },
  {
    id: "snowman",
    char: "☃️",
    label: "Snowman",
    keywords: ["winter", "season", "cold", "weather", "christmas"],
  },
  {
    id: "cyclone",
    char: "🌀",
    label: "Cyclone",
    keywords: ["weather", "swirl", "blue", "cloud", "vortex"],
  },
  {
    id: "rainbow",
    char: "🌈",
    label: "Rainbow",
    keywords: ["nature", "happy", "unicorn_face", "photo", "sky"],
  },
  {
    id: "umbrella-with-rain-drops",
    char: "☔",
    label: "Umbrella With Rain Drops",
    keywords: ["rainy", "weather", "spring", "clothing", "drop"],
  },
  {
    id: "droplet",
    char: "💧",
    label: "Droplet",
    keywords: ["water", "drip", "faucet", "spring", "cold"],
  },
  {
    id: "sweat-droplets",
    char: "💦",
    label: "Sweat Droplets",
    keywords: ["water", "drip", "oops", "comic", "drops"],
  },
  {
    id: "fire",
    char: "🔥",
    label: "Fire",
    keywords: ["hot", "cook", "flame", "burn", "lit"],
  },
  {
    id: "collision",
    char: "💥",
    label: "Collision",
    keywords: ["bomb", "explode", "explosion", "blown", "bang"],
  },
  {
    id: "sparkles",
    char: "✨",
    label: "Sparkles",
    keywords: ["stars", "shine", "shiny", "cool", "awesome"],
  },
  {
    id: "star",
    char: "⭐",
    label: "Star",
    keywords: ["night", "yellow", "gold", "medium", "white"],
  },
  {
    id: "glowing-star",
    char: "🌟",
    label: "Glowing Star",
    keywords: ["night", "sparkle", "awesome", "good", "magic"],
  },
  {
    id: "shooting-star",
    char: "🌠",
    label: "Shooting Star",
    keywords: ["night", "photo", "activity", "falling", "meteoroid"],
  },
  {
    id: "crescent-moon",
    char: "🌙",
    label: "Crescent Moon",
    keywords: ["night", "sleep", "sky", "evening", "magic"],
  },
  {
    id: "full-moon",
    char: "🌕",
    label: "Full Moon",
    keywords: ["nature", "yellow", "twilight", "planet", "space"],
  },
  {
    id: "new-moon",
    char: "🌑",
    label: "New Moon",
    keywords: ["nature", "twilight", "planet", "space", "night"],
  },
  {
    id: "globe-showing-europe-africa",
    char: "🌍",
    label: "Globe Showing Europe Africa",
    keywords: ["globe", "world", "earth", "international", "planet"],
  },
  {
    id: "seedling",
    char: "🌱",
    label: "Seedling",
    keywords: ["plant", "nature", "grass", "lawn", "spring"],
  },
  {
    id: "herb",
    char: "🌿",
    label: "Herb",
    keywords: ["vegetable", "plant", "medicine", "weed", "grass"],
  },
  {
    id: "four-leaf-clover",
    char: "🍀",
    label: "Four Leaf Clover",
    keywords: ["vegetable", "plant", "nature", "lucky", "irish"],
  },
  {
    id: "palm-tree",
    char: "🌴",
    label: "Palm Tree",
    keywords: ["plant", "vegetable", "nature", "summer", "beach"],
  },
  {
    id: "cactus",
    char: "🌵",
    label: "Cactus",
    keywords: ["vegetable", "plant", "nature", "desert"],
  },
  {
    id: "tulip",
    char: "🌷",
    label: "Tulip",
    keywords: ["flowers", "plant", "nature", "summer", "spring"],
  },
  {
    id: "cherry-blossom",
    char: "🌸",
    label: "Cherry Blossom",
    keywords: ["nature", "plant", "spring", "flower", "pink"],
  },
  {
    id: "rose",
    char: "🌹",
    label: "Rose",
    keywords: ["flowers", "valentines", "love", "spring", "flower"],
  },
  {
    id: "hibiscus",
    char: "🌺",
    label: "Hibiscus",
    keywords: ["plant", "vegetable", "flowers", "beach", "flower"],
  },
  {
    id: "sunflower",
    char: "🌻",
    label: "Sunflower",
    keywords: ["nature", "plant", "fall", "flower", "sun"],
  },
  {
    id: "blossom",
    char: "🌼",
    label: "Blossom",
    keywords: ["nature", "flowers", "yellow", "daisy", "flower"],
  },
  {
    id: "fallen-leaf",
    char: "🍂",
    label: "Fallen Leaf",
    keywords: ["nature", "plant", "vegetable", "leaves", "autumn"],
  },
  {
    id: "maple-leaf",
    char: "🍁",
    label: "Maple Leaf",
    keywords: ["nature", "plant", "vegetable", "ca", "fall"],
  },
  {
    id: "leaf-fluttering-in-wind",
    char: "🍃",
    label: "Leaf Fluttering In Wind",
    keywords: ["nature", "plant", "tree", "vegetable", "grass"],
  },
  {
    id: "evergreen-tree",
    char: "🌲",
    label: "Evergreen Tree",
    keywords: ["plant", "nature", "fir", "pine", "wood"],
  },
  {
    id: "deciduous-tree",
    char: "🌳",
    label: "Deciduous Tree",
    keywords: ["plant", "nature", "rounded", "shedding", "wood"],
  },
  // --- Food & drink ---
  {
    id: "red-apple",
    char: "🍎",
    label: "Red Apple",
    keywords: ["fruit", "mac", "school", "delicious", "plant"],
  },
  {
    id: "green-apple",
    char: "🍏",
    label: "Green Apple",
    keywords: ["fruit", "nature", "delicious", "golden", "granny"],
  },
  {
    id: "pear",
    char: "🍐",
    label: "Pear",
    keywords: ["fruit", "nature", "food", "plant"],
  },
  {
    id: "tangerine",
    char: "🍊",
    label: "Tangerine",
    keywords: ["food", "fruit", "nature", "orange", "mandarin"],
  },
  {
    id: "lemon",
    char: "🍋",
    label: "Lemon",
    keywords: ["fruit", "nature", "citrus", "lemonade", "plant"],
  },
  {
    id: "banana",
    char: "🍌",
    label: "Banana",
    keywords: ["fruit", "food", "monkey", "plant", "plantain"],
  },
  {
    id: "watermelon",
    char: "🍉",
    label: "Watermelon",
    keywords: ["fruit", "food", "picnic", "summer", "plant"],
  },
  {
    id: "grapes",
    char: "🍇",
    label: "Grapes",
    keywords: ["fruit", "food", "wine", "grape", "plant"],
  },
  {
    id: "strawberry",
    char: "🍓",
    label: "Strawberry",
    keywords: ["fruit", "food", "nature", "berry", "plant"],
  },
  {
    id: "melon",
    char: "🍈",
    label: "Melon",
    keywords: ["fruit", "nature", "food", "cantaloupe", "honeydew"],
  },
  {
    id: "cherries",
    char: "🍒",
    label: "Cherries",
    keywords: ["food", "fruit", "berries", "cherry", "plant"],
  },
  {
    id: "peach",
    char: "🍑",
    label: "Peach",
    keywords: ["fruit", "nature", "food", "bottom", "butt"],
  },
  {
    id: "mango",
    char: "🥭",
    label: "Mango",
    keywords: ["fruit", "food", "tropical"],
  },
  {
    id: "pineapple",
    char: "🍍",
    label: "Pineapple",
    keywords: ["fruit", "nature", "food", "plant"],
  },
  {
    id: "coconut",
    char: "🥥",
    label: "Coconut",
    keywords: ["fruit", "nature", "food", "palm", "cocoanut"],
  },
  {
    id: "kiwi-fruit",
    char: "🥝",
    label: "Kiwi Fruit",
    keywords: ["fruit", "food", "chinese", "gooseberry", "kiwifruit"],
  },
  {
    id: "tomato",
    char: "🍅",
    label: "Tomato",
    keywords: ["fruit", "vegetable", "nature", "food", "plant"],
  },
  { id: "avocado", char: "🥑", label: "Avocado", keywords: ["fruit", "food"] },
  {
    id: "broccoli",
    char: "🥦",
    label: "Broccoli",
    keywords: ["fruit", "food", "vegetable", "cabbage", "wild"],
  },
  {
    id: "leafy-green",
    char: "🥬",
    label: "Leafy Green",
    keywords: ["food", "vegetable", "plant", "cabbage", "kale"],
  },
  {
    id: "cucumber",
    char: "🥒",
    label: "Cucumber",
    keywords: ["fruit", "food", "pickle", "gherkin", "vegetable"],
  },
  {
    id: "hot-pepper",
    char: "🌶️",
    label: "Hot Pepper",
    keywords: ["food", "spicy", "chilli", "chili", "plant"],
  },
  {
    id: "ear-of-corn",
    char: "🌽",
    label: "Ear Of Corn",
    keywords: ["food", "vegetable", "plant", "cob", "maize"],
  },
  {
    id: "carrot",
    char: "🥕",
    label: "Carrot",
    keywords: ["vegetable", "food", "orange"],
  },
  {
    id: "potato",
    char: "🥔",
    label: "Potato",
    keywords: ["food", "tuber", "vegatable", "starch", "baked"],
  },
  {
    id: "roasted-sweet-potato",
    char: "🍠",
    label: "Roasted Sweet Potato",
    keywords: ["food", "nature", "plant", "goguma", "yam"],
  },
  {
    id: "croissant",
    char: "🥐",
    label: "Croissant",
    keywords: ["food", "bread", "french", "breakfast", "crescent"],
  },
  {
    id: "bread",
    char: "🍞",
    label: "Bread",
    keywords: ["food", "wheat", "breakfast", "toast", "loaf"],
  },
  {
    id: "cheese-wedge",
    char: "🧀",
    label: "Cheese Wedge",
    keywords: ["food", "chadder", "swiss"],
  },
  {
    id: "egg",
    char: "🥚",
    label: "Egg",
    keywords: ["food", "chicken", "breakfast", "easter_egg"],
  },
  {
    id: "cooking",
    char: "🍳",
    label: "Cooking",
    keywords: ["food", "breakfast", "kitchen", "egg", "skillet"],
  },
  {
    id: "pancakes",
    char: "🥞",
    label: "Pancakes",
    keywords: ["food", "breakfast", "flapjacks", "hotcakes", "brunch"],
  },
  {
    id: "bacon",
    char: "🥓",
    label: "Bacon",
    keywords: ["food", "breakfast", "pork", "pig", "meat"],
  },
  {
    id: "cut-of-meat",
    char: "🥩",
    label: "Cut Of Meat",
    keywords: ["food", "cow", "meat", "cut", "chop"],
  },
  {
    id: "poultry-leg",
    char: "🍗",
    label: "Poultry Leg",
    keywords: ["food", "meat", "drumstick", "bird", "chicken"],
  },
  {
    id: "hot-dog",
    char: "🌭",
    label: "Hot Dog",
    keywords: ["food", "frankfurter", "america", "hotdog", "redhot"],
  },
  {
    id: "hamburger",
    char: "🍔",
    label: "Hamburger",
    keywords: ["meat", "beef", "cheeseburger", "mcdonalds"],
  },
  {
    id: "french-fries",
    char: "🍟",
    label: "French Fries",
    keywords: ["chips", "snack", "potato"],
  },
  {
    id: "pizza",
    char: "🍕",
    label: "Pizza",
    keywords: ["food", "party", "italy", "cheese", "pepperoni"],
  },
  {
    id: "sandwich",
    char: "🥪",
    label: "Sandwich",
    keywords: ["food", "lunch", "bread", "toast", "bakery"],
  },
  { id: "taco", char: "🌮", label: "Taco", keywords: ["food", "mexican"] },
  {
    id: "burrito",
    char: "🌯",
    label: "Burrito",
    keywords: ["food", "mexican", "wrap"],
  },
  {
    id: "canned-food",
    char: "🥫",
    label: "Canned Food",
    keywords: ["food", "soup", "tomatoes", "can", "preserve"],
  },
  {
    id: "spaghetti",
    char: "🍝",
    label: "Spaghetti",
    keywords: ["food", "italian", "pasta", "noodle"],
  },
  {
    id: "steaming-bowl",
    char: "🍜",
    label: "Steaming Bowl",
    keywords: ["food", "japanese", "noodle", "chopsticks", "ramen"],
  },
  {
    id: "curry-rice",
    char: "🍛",
    label: "Curry Rice",
    keywords: ["food", "spicy", "hot", "indian"],
  },
  {
    id: "sushi",
    char: "🍣",
    label: "Sushi",
    keywords: ["food", "fish", "japanese", "rice", "sashimi"],
  },
  {
    id: "bento-box",
    char: "🍱",
    label: "Bento Box",
    keywords: ["food", "japanese", "box", "lunch", "assets"],
  },
  {
    id: "rice-ball",
    char: "🍙",
    label: "Rice Ball",
    keywords: ["food", "japanese", "onigiri", "omusubi"],
  },
  {
    id: "cooked-rice",
    char: "🍚",
    label: "Cooked Rice",
    keywords: ["food", "asian", "boiled", "bowl", "steamed"],
  },
  {
    id: "shaved-ice",
    char: "🍧",
    label: "Shaved Ice",
    keywords: ["hot", "dessert", "summer", "cone", "snow"],
  },
  {
    id: "ice-cream",
    char: "🍨",
    label: "Ice Cream",
    keywords: ["food", "hot", "dessert", "bowl", "sweet"],
  },
  {
    id: "soft-ice-cream",
    char: "🍦",
    label: "Soft Ice Cream",
    keywords: ["food", "hot", "dessert", "summer", "icecream"],
  },
  {
    id: "doughnut",
    char: "🍩",
    label: "Doughnut",
    keywords: ["food", "dessert", "snack", "sweet", "donut"],
  },
  {
    id: "cookie",
    char: "🍪",
    label: "Cookie",
    keywords: ["food", "snack", "oreo", "chocolate", "sweet"],
  },
  {
    id: "birthday-cake",
    char: "🎂",
    label: "Birthday Cake",
    keywords: ["food", "dessert", "cake", "candles", "celebration"],
  },
  {
    id: "shortcake",
    char: "🍰",
    label: "Shortcake",
    keywords: ["food", "dessert", "cake", "pastry", "piece"],
  },
  {
    id: "cupcake",
    char: "🧁",
    label: "Cupcake",
    keywords: ["food", "dessert", "bakery", "sweet", "cake"],
  },
  {
    id: "pie",
    char: "🥧",
    label: "Pie",
    keywords: ["food", "dessert", "pastry", "filling", "sweet"],
  },
  {
    id: "chocolate-bar",
    char: "🍫",
    label: "Chocolate Bar",
    keywords: ["food", "snack", "dessert", "sweet", "candy"],
  },
  {
    id: "candy",
    char: "🍬",
    label: "Candy",
    keywords: ["snack", "dessert", "sweet", "lolly"],
  },
  {
    id: "lollipop",
    char: "🍭",
    label: "Lollipop",
    keywords: ["food", "snack", "candy", "sweet", "dessert"],
  },
  {
    id: "honey-pot",
    char: "🍯",
    label: "Honey Pot",
    keywords: ["bees", "sweet", "kitchen", "honeypot"],
  },
  {
    id: "popcorn",
    char: "🍿",
    label: "Popcorn",
    keywords: ["food", "films", "snack", "drama", "corn"],
  },
  { id: "salt", char: "🧂", label: "Salt", keywords: ["condiment", "shaker"] },
  {
    id: "baby-bottle",
    char: "🍼",
    label: "Baby Bottle",
    keywords: ["food", "container", "milk", "drink", "feeding"],
  },
  {
    id: "glass-of-milk",
    char: "🥛",
    label: "Glass Of Milk",
    keywords: ["beverage", "drink", "cow"],
  },
  {
    id: "hot-beverage",
    char: "☕",
    label: "Hot Beverage",
    keywords: ["beverage", "caffeine", "latte", "espresso", "coffee"],
  },
  {
    id: "teacup-without-handle",
    char: "🍵",
    label: "Teacup Without Handle",
    keywords: ["drink", "bowl", "breakfast", "green", "british"],
  },
  {
    id: "beverage-box",
    char: "🧃",
    label: "Beverage Box",
    keywords: ["drink", "juice", "straw", "sweet"],
  },
  {
    id: "cup-with-straw",
    char: "🥤",
    label: "Cup With Straw",
    keywords: ["drink", "soda", "go", "juice", "malt"],
  },
  {
    id: "bubble-tea",
    char: "🧋",
    label: "Bubble Tea",
    keywords: ["taiwan", "boba", "straw", "momi", "pearl"],
  },
  {
    id: "beer-mug",
    char: "🍺",
    label: "Beer Mug",
    keywords: ["relax", "beverage", "drink", "drunk", "party"],
  },
  {
    id: "clinking-beer-mugs",
    char: "🍻",
    label: "Clinking Beer Mugs",
    keywords: ["relax", "beverage", "drink", "drunk", "party"],
  },
  {
    id: "clinking-glasses",
    char: "🥂",
    label: "Clinking Glasses",
    keywords: ["beverage", "drink", "party", "alcohol", "celebrate"],
  },
  {
    id: "wine-glass",
    char: "🍷",
    label: "Wine Glass",
    keywords: ["drink", "beverage", "drunk", "alcohol", "booze"],
  },
  {
    id: "tropical-drink",
    char: "🍹",
    label: "Tropical Drink",
    keywords: ["beverage", "cocktail", "summer", "beach", "alcohol"],
  },
  {
    id: "cocktail-glass",
    char: "🍸",
    label: "Cocktail Glass",
    keywords: ["drink", "drunk", "alcohol", "beverage", "booze"],
  },
  {
    id: "chopsticks",
    char: "🥢",
    label: "Chopsticks",
    keywords: ["food", "hashi", "jeotgarak", "kuaizi"],
  },
  // --- Activities & sports ---
  {
    id: "soccer-ball",
    char: "⚽",
    label: "Soccer Ball",
    keywords: ["sports", "football"],
  },
  {
    id: "basketball",
    char: "🏀",
    label: "Basketball",
    keywords: ["sports", "balls", "nba", "ball", "hoop"],
  },
  {
    id: "american-football",
    char: "🏈",
    label: "American Football",
    keywords: ["sports", "balls", "nfl", "ball", "gridiron"],
  },
  {
    id: "baseball",
    char: "⚾",
    label: "Baseball",
    keywords: ["sports", "balls", "ball", "softball"],
  },
  {
    id: "softball",
    char: "🥎",
    label: "Softball",
    keywords: ["sports", "balls", "ball", "game", "glove"],
  },
  {
    id: "tennis",
    char: "🎾",
    label: "Tennis",
    keywords: ["sports", "balls", "green", "ball", "racket"],
  },
  {
    id: "volleyball",
    char: "🏐",
    label: "Volleyball",
    keywords: ["sports", "balls", "ball", "game"],
  },
  {
    id: "rugby-football",
    char: "🏉",
    label: "Rugby Football",
    keywords: ["sports", "team", "ball", "league", "union"],
  },
  {
    id: "flying-disc",
    char: "🥏",
    label: "Flying Disc",
    keywords: ["sports", "frisbee", "ultimate", "game", "golf"],
  },
  {
    id: "pool-8-ball",
    char: "🎱",
    label: "Pool 8 Ball",
    keywords: ["pool", "hobby", "game", "luck", "magic"],
  },
  {
    id: "ping-pong",
    char: "🏓",
    label: "Ping Pong",
    keywords: ["sports", "pingpong", "ball", "bat", "game"],
  },
  {
    id: "badminton",
    char: "🏸",
    label: "Badminton",
    keywords: ["sports", "birdie", "game", "racquet", "shuttlecock"],
  },
  {
    id: "ice-hockey",
    char: "🏒",
    label: "Ice Hockey",
    keywords: ["sports", "game", "puck", "stick"],
  },
  {
    id: "field-hockey",
    char: "🏑",
    label: "Field Hockey",
    keywords: ["sports", "ball", "game", "stick"],
  },
  {
    id: "boxing-glove",
    char: "🥊",
    label: "Boxing Glove",
    keywords: ["sports", "fighting"],
  },
  {
    id: "martial-arts-uniform",
    char: "🥋",
    label: "Martial Arts Uniform",
    keywords: ["judo", "karate", "taekwondo"],
  },
  {
    id: "running-shirt",
    char: "🎽",
    label: "Running Shirt",
    keywords: ["play", "pageant", "athletics", "marathon", "sash"],
  },
  {
    id: "skateboard",
    char: "🛹",
    label: "Skateboard",
    keywords: ["board", "skate"],
  },
  {
    id: "sled",
    char: "🛷",
    label: "Sled",
    keywords: ["sleigh", "luge", "toboggan", "sledge"],
  },
  {
    id: "curling-stone",
    char: "🥌",
    label: "Curling Stone",
    keywords: ["sports", "game", "rock"],
  },
  {
    id: "skier",
    char: "⛷️",
    label: "Skier",
    keywords: ["sports", "winter", "snow", "ski"],
  },
  {
    id: "snowboarder",
    char: "🏂",
    label: "Snowboarder",
    keywords: ["sports", "winter", "ski", "snow", "snowboard"],
  },
  {
    id: "person-lifting-weights",
    char: "🏋️",
    label: "Person Lifting Weights",
    keywords: ["sports", "training", "exercise", "bodybuilder", "gym"],
  },
  {
    id: "trophy",
    char: "🏆",
    label: "Trophy",
    keywords: ["win", "award", "contest", "place", "ftw"],
  },
  {
    id: "1st-place-medal",
    char: "🥇",
    label: "1st Place Medal",
    keywords: ["award", "winning", "first", "gold"],
  },
  {
    id: "2nd-place-medal",
    char: "🥈",
    label: "2nd Place Medal",
    keywords: ["award", "second", "silver"],
  },
  {
    id: "3rd-place-medal",
    char: "🥉",
    label: "3rd Place Medal",
    keywords: ["award", "third", "bronze"],
  },
  {
    id: "sports-medal",
    char: "🏅",
    label: "Sports Medal",
    keywords: ["award", "winning", "gold", "winner"],
  },
  {
    id: "ticket",
    char: "🎫",
    label: "Ticket",
    keywords: ["event", "concert", "pass", "activity", "admission"],
  },
  {
    id: "circus-tent",
    char: "🎪",
    label: "Circus Tent",
    keywords: ["festival", "carnival", "party", "activity", "big"],
  },
  {
    id: "performing-arts",
    char: "🎭",
    label: "Performing Arts",
    keywords: ["acting", "theater", "drama", "activity", "art"],
  },
  {
    id: "artist-palette",
    char: "🎨",
    label: "Artist Palette",
    keywords: ["design", "paint", "draw", "colors", "activity"],
  },
  {
    id: "clapper-board",
    char: "🎬",
    label: "Clapper Board",
    keywords: ["movie", "film", "record", "activity", "clapboard"],
  },
  {
    id: "microphone",
    char: "🎤",
    label: "Microphone",
    keywords: ["sound", "music", "pa", "sing", "talkshow"],
  },
  {
    id: "headphone",
    char: "🎧",
    label: "Headphone",
    keywords: ["music", "score", "gadgets", "activity", "earbud"],
  },
  {
    id: "musical-score",
    char: "🎼",
    label: "Musical Score",
    keywords: ["treble", "clef", "compose", "activity", "entertainment"],
  },
  {
    id: "musical-keyboard",
    char: "🎹",
    label: "Musical Keyboard",
    keywords: ["piano", "instrument", "compose", "activity", "entertainment"],
  },
  {
    id: "drum",
    char: "🥁",
    label: "Drum",
    keywords: ["music", "instrument", "drumsticks", "snare"],
  },
  {
    id: "saxophone",
    char: "🎷",
    label: "Saxophone",
    keywords: ["music", "instrument", "jazz", "blues", "activity"],
  },
  {
    id: "guitar",
    char: "🎸",
    label: "Guitar",
    keywords: ["music", "instrument", "activity", "bass", "electric"],
  },
  {
    id: "banjo",
    char: "🪕",
    label: "Banjo",
    keywords: [
      "music",
      "instructment",
      "activity",
      "entertainment",
      "instrument",
    ],
  },
  {
    id: "violin",
    char: "🎻",
    label: "Violin",
    keywords: ["music", "instrument", "orchestra", "symphony", "activity"],
  },
  {
    id: "game-die",
    char: "🎲",
    label: "Game Die",
    keywords: ["dice", "random", "tabletop", "play", "luck"],
  },
  {
    id: "chess-pawn",
    char: "♟️",
    label: "Chess Pawn",
    keywords: ["expendable", "black", "dupe", "game", "piece"],
  },
  {
    id: "dart",
    char: "🎯",
    label: "Dart",
    keywords: ["game", "play", "bar", "target", "bullseye", "dart"],
  },
  {
    id: "bowling",
    char: "🎳",
    label: "Bowling",
    keywords: ["sports", "fun", "play", "ball", "game"],
  },
  {
    id: "video-game",
    char: "🎮",
    label: "Video Game",
    keywords: ["play", "console", "ps4", "controller", "entertainment"],
  },
  {
    id: "party-popper",
    char: "🎉",
    label: "Party Popper",
    keywords: ["party", "congratulations", "birthday", "magic", "circus"],
  },
  {
    id: "confetti-ball",
    char: "🎊",
    label: "Confetti Ball",
    keywords: ["festival", "party", "birthday", "circus", "activity"],
  },
  {
    id: "balloon",
    char: "🎈",
    label: "Balloon",
    keywords: ["party", "celebration", "birthday", "circus", "activity"],
  },
  {
    id: "wrapped-gift",
    char: "🎁",
    label: "Wrapped Gift",
    keywords: ["present", "birthday", "christmas", "xmas", "box"],
  },
  {
    id: "christmas-tree",
    char: "🎄",
    label: "Christmas Tree",
    keywords: ["festival", "vacation", "december", "xmas", "celebration"],
  },
  {
    id: "jack-o-lantern",
    char: "🎃",
    label: "Jack O Lantern",
    keywords: ["halloween", "light", "pumpkin", "creepy", "fall"],
  },
  // --- Travel & places ---
  {
    id: "automobile",
    char: "🚗",
    label: "Automobile",
    keywords: ["red", "transportation", "vehicle", "car", "side"],
  },
  {
    id: "taxi",
    char: "🚕",
    label: "Taxi",
    keywords: ["uber", "vehicle", "cars", "transportation", "new"],
  },
  {
    id: "bus",
    char: "🚌",
    label: "Bus",
    keywords: ["car", "vehicle", "transportation", "school"],
  },
  {
    id: "police-car",
    char: "🚓",
    label: "Police Car",
    keywords: ["vehicle", "cars", "transportation", "law", "legal"],
  },
  {
    id: "ambulance",
    char: "🚑",
    label: "Ambulance",
    keywords: ["health", "911", "hospital", "vehicle"],
  },
  {
    id: "fire-engine",
    char: "🚒",
    label: "Fire Engine",
    keywords: ["transportation", "cars", "vehicle", "department", "truck"],
  },
  {
    id: "delivery-truck",
    char: "🚚",
    label: "Delivery Truck",
    keywords: ["cars", "transportation", "vehicle", "resources"],
  },
  {
    id: "kick-scooter",
    char: "🛴",
    label: "Kick Scooter",
    keywords: ["vehicle", "kick", "razor"],
  },
  {
    id: "bicycle",
    char: "🚲",
    label: "Bicycle",
    keywords: ["bike", "sports", "exercise", "hipster", "push"],
  },
  {
    id: "motorcycle",
    char: "🏍️",
    label: "Motorcycle",
    keywords: ["race", "sports", "fast", "motorbike", "racing"],
  },
  {
    id: "airplane",
    char: "✈️",
    label: "Airplane",
    keywords: ["vehicle", "transportation", "flight", "fly", "aeroplane"],
  },
  {
    id: "small-airplane",
    char: "🛩️",
    label: "Small Airplane",
    keywords: ["flight", "transportation", "fly", "vehicle", "aeroplane"],
  },
  {
    id: "helicopter",
    char: "🚁",
    label: "Helicopter",
    keywords: ["transportation", "vehicle", "fly"],
  },
  {
    id: "rocket",
    char: "🚀",
    label: "Rocket",
    keywords: ["launch", "ship", "staffmode", "nasa", "outer_space"],
  },
  {
    id: "flying-saucer",
    char: "🛸",
    label: "Flying Saucer",
    keywords: ["transportation", "vehicle", "ufo", "alien", "extraterrestrial"],
  },
  {
    id: "sailboat",
    char: "⛵",
    label: "Sailboat",
    keywords: ["ship", "summer", "transportation", "water", "sailing"],
  },
  {
    id: "speedboat",
    char: "🚤",
    label: "Speedboat",
    keywords: ["ship", "transportation", "vehicle", "summer", "boat"],
  },
  {
    id: "ship",
    char: "🚢",
    label: "Ship",
    keywords: ["transportation", "titanic", "deploy", "boat", "cruise"],
  },
  {
    id: "anchor",
    char: "⚓",
    label: "Anchor",
    keywords: ["ship", "ferry", "sea", "boat", "admiralty"],
  },
  {
    id: "fuel-pump",
    char: "⛽",
    label: "Fuel Pump",
    keywords: ["petroleum", "diesel", "fuelpump", "petrol"],
  },
  {
    id: "traffic-light",
    char: "🚦",
    label: "Traffic Light",
    keywords: ["transportation", "driving", "semaphore", "signal"],
  },
  {
    id: "stop-sign",
    char: "🛑",
    label: "Stop Sign",
    keywords: ["stop", "octagonal"],
  },
  {
    id: "construction",
    char: "🚧",
    label: "Construction",
    keywords: ["wip", "progress", "caution", "warning", "barrier"],
  },
  {
    id: "world-map",
    char: "🗺️",
    label: "World Map",
    keywords: ["location", "direction", "travel"],
  },
  {
    id: "globe-with-meridians",
    char: "🌐",
    label: "Globe With Meridians",
    keywords: ["earth", "international", "world", "internet", "interweb"],
  },
  {
    id: "compass",
    char: "🧭",
    label: "Compass",
    keywords: ["magnetic", "navigation", "orienteering"],
  },
  {
    id: "mountain",
    char: "⛰️",
    label: "Mountain",
    keywords: ["photo", "nature", "environment"],
  },
  {
    id: "snow-capped-mountain",
    char: "🏔️",
    label: "Snow Capped Mountain",
    keywords: ["photo", "nature", "environment", "winter", "cold"],
  },
  {
    id: "volcano",
    char: "🌋",
    label: "Volcano",
    keywords: ["photo", "nature", "disaster", "eruption", "mountain"],
  },
  {
    id: "desert",
    char: "🏜️",
    label: "Desert",
    keywords: ["photo", "warm", "saharah"],
  },
  {
    id: "beach-with-umbrella",
    char: "🏖️",
    label: "Beach With Umbrella",
    keywords: ["weather", "summer", "sunny", "sand", "mojito"],
  },
  {
    id: "desert-island",
    char: "🏝️",
    label: "Desert Island",
    keywords: ["photo", "tropical", "mojito"],
  },
  {
    id: "national-park",
    char: "🏞️",
    label: "National Park",
    keywords: ["photo", "environment", "nature"],
  },
  {
    id: "stadium",
    char: "🏟️",
    label: "Stadium",
    keywords: ["photo", "place", "sports", "concert", "venue"],
  },
  { id: "house", char: "🏠", label: "House", keywords: ["building", "home"] },
  {
    id: "house-with-garden",
    char: "🏡",
    label: "House With Garden",
    keywords: ["home", "plant", "nature", "building", "tree"],
  },
  {
    id: "office-building",
    char: "🏢",
    label: "Office Building",
    keywords: ["building", "bureau", "work", "city", "high"],
  },
  {
    id: "hospital",
    char: "🏥",
    label: "Hospital",
    keywords: ["building", "health", "surgery", "doctor", "cross"],
  },
  {
    id: "bank",
    char: "🏦",
    label: "Bank",
    keywords: ["building", "money", "sales", "cash", "business"],
  },
  {
    id: "hotel",
    char: "🏨",
    label: "Hotel",
    keywords: ["building", "accomodation", "checkin", "accommodation", "h"],
  },
  {
    id: "school",
    char: "🏫",
    label: "School",
    keywords: ["building", "student", "education", "learn", "teach"],
  },
  {
    id: "church",
    char: "⛪",
    label: "Church",
    keywords: ["building", "religion", "christ", "christian", "cross"],
  },
  {
    id: "castle",
    char: "🏰",
    label: "Castle",
    keywords: ["building", "royalty", "history", "european", "turrets"],
  },
  {
    id: "tent",
    char: "⛺",
    label: "Tent",
    keywords: ["photo", "camping", "outdoors"],
  },
  {
    id: "sunrise",
    char: "🌅",
    label: "Sunrise",
    keywords: ["morning", "view", "vacation", "photo", "sun"],
  },
  {
    id: "sunset",
    char: "🌇",
    label: "Sunset",
    keywords: ["photo", "dawn", "building", "buildings", "city"],
  },
  {
    id: "night-with-stars",
    char: "🌃",
    label: "Night With Stars",
    keywords: ["evening", "city", "downtown", "star", "starry"],
  },
  {
    id: "cityscape",
    char: "🏙️",
    label: "Cityscape",
    keywords: ["photo", "urban", "building", "city", "skyline"],
  },
  {
    id: "milky-way",
    char: "🌌",
    label: "Milky Way",
    keywords: ["photo", "space", "stars", "galaxy", "night"],
  },
  {
    id: "ferris-wheel",
    char: "🎡",
    label: "Ferris Wheel",
    keywords: ["photo", "carnival", "londoneye", "activity", "amusement"],
  },
  {
    id: "roller-coaster",
    char: "🎢",
    label: "Roller Coaster",
    keywords: ["carnival", "playground", "photo", "fun", "activity"],
  },
  {
    id: "carousel-horse",
    char: "🎠",
    label: "Carousel Horse",
    keywords: ["photo", "carnival", "activity", "entertainment", "fairground"],
  },
  // --- Objects ---
  {
    id: "watch",
    char: "⌚",
    label: "Watch",
    keywords: ["time", "accessories", "apple", "clock", "timepiece"],
  },
  {
    id: "mobile-phone",
    char: "📱",
    label: "Mobile Phone",
    keywords: ["technology", "apple", "gadgets", "dial", "cell"],
  },
  {
    id: "laptop",
    char: "💻",
    label: "Laptop",
    keywords: ["technology", "screen", "display", "monitor", "computer"],
  },
  {
    id: "desktop-computer",
    char: "🖥️",
    label: "Desktop Computer",
    keywords: ["technology", "computing", "screen", "imac"],
  },
  {
    id: "keyboard",
    char: "⌨️",
    label: "Keyboard",
    keywords: ["technology", "computer", "type", "input", "text"],
  },
  {
    id: "printer",
    char: "🖨️",
    label: "Printer",
    keywords: ["paper", "ink", "computer"],
  },
  {
    id: "camera",
    char: "📷",
    label: "Camera",
    keywords: ["gadgets", "photography", "digital", "entertainment", "photo"],
  },
  {
    id: "video-camera",
    char: "📹",
    label: "Video Camera",
    keywords: ["film", "record", "camcorder", "entertainment"],
  },
  {
    id: "movie-camera",
    char: "🎥",
    label: "Movie Camera",
    keywords: ["film", "record", "activity", "cinema", "entertainment"],
  },
  {
    id: "television",
    char: "📺",
    label: "Television",
    keywords: ["technology", "program", "oldschool", "show", "entertainment"],
  },
  {
    id: "radio",
    char: "📻",
    label: "Radio",
    keywords: ["communication", "music", "podcast", "program", "digital"],
  },
  {
    id: "battery",
    char: "🔋",
    label: "Battery",
    keywords: ["power", "energy", "sustain", "aa", "phone"],
  },
  {
    id: "electric-plug",
    char: "🔌",
    label: "Electric Plug",
    keywords: ["charger", "power", "ac", "adaptor", "cable"],
  },
  {
    id: "light-bulb",
    char: "💡",
    label: "Light Bulb",
    keywords: ["light", "electricity", "idea", "comic", "electric"],
  },
  {
    id: "flashlight",
    char: "🔦",
    label: "Flashlight",
    keywords: ["dark", "camping", "sight", "night", "electric"],
  },
  {
    id: "candle",
    char: "🕯️",
    label: "Candle",
    keywords: ["fire", "wax", "light"],
  },
  {
    id: "notebook",
    char: "📓",
    label: "Notebook",
    keywords: ["stationery", "record", "notes", "paper", "study"],
  },
  {
    id: "open-book",
    char: "📖",
    label: "Open Book",
    keywords: ["book", "read", "library", "knowledge", "literature"],
  },
  {
    id: "bookmark",
    char: "🔖",
    label: "Bookmark",
    keywords: ["favorite", "label", "save", "mark", "price"],
  },
  {
    id: "newspaper",
    char: "📰",
    label: "Newspaper",
    keywords: ["press", "headline", "communication", "news", "paper"],
  },
  {
    id: "envelope",
    char: "✉️",
    label: "Envelope",
    keywords: ["letter", "postal", "inbox", "communication", "email"],
  },
  {
    id: "package",
    char: "📦",
    label: "Package",
    keywords: ["mail", "gift", "cardboard", "box", "moving"],
  },
  {
    id: "postbox",
    char: "📮",
    label: "Postbox",
    keywords: ["email", "letter", "envelope", "communication", "mail"],
  },
  {
    id: "money-bag",
    char: "💰",
    label: "Money Bag",
    keywords: ["dollar", "payment", "coins", "sale", "cream"],
  },
  {
    id: "dollar-banknote",
    char: "💵",
    label: "Dollar Banknote",
    keywords: ["money", "sales", "bill", "currency", "american"],
  },
  {
    id: "credit-card",
    char: "💳",
    label: "Credit Card",
    keywords: ["money", "sales", "dollar", "bill", "payment"],
  },
  {
    id: "gem-stone",
    char: "💎",
    label: "Gem Stone",
    keywords: ["blue", "ruby", "diamond", "jewelry", "gemstone"],
  },
  {
    id: "toolbox",
    char: "🧰",
    label: "Toolbox",
    keywords: ["tools", "diy", "fix", "maintainer", "mechanic"],
  },
  {
    id: "hammer",
    char: "🔨",
    label: "Hammer",
    keywords: ["tools", "build", "create", "claw", "handyman"],
  },
  {
    id: "wrench",
    char: "🔧",
    label: "Wrench",
    keywords: ["tools", "diy", "ikea", "fix", "maintainer"],
  },
  {
    id: "gear",
    char: "⚙️",
    label: "Gear",
    keywords: ["cog", "cogwheel", "tool"],
  },
  {
    id: "link",
    char: "🔗",
    label: "Link",
    keywords: ["rings", "url", "chain", "hyperlink", "linked"],
  },
  {
    id: "chains",
    char: "⛓️",
    label: "Chains",
    keywords: ["lock", "arrest", "chain"],
  },
  {
    id: "magnet",
    char: "🧲",
    label: "Magnet",
    keywords: ["attraction", "magnetic", "horseshoe"],
  },
  {
    id: "microscope",
    char: "🔬",
    label: "Microscope",
    keywords: ["laboratory", "experiment", "zoomin", "science", "study"],
  },
  {
    id: "telescope",
    char: "🔭",
    label: "Telescope",
    keywords: ["stars", "space", "zoom", "science", "astronomy"],
  },
  {
    id: "test-tube",
    char: "🧪",
    label: "Test Tube",
    keywords: ["chemistry", "experiment", "lab", "science", "chemist"],
  },
  {
    id: "dna",
    char: "🧬",
    label: "Dna",
    keywords: ["biologist", "genetics", "life", "double", "evolution"],
  },
  {
    id: "syringe",
    char: "💉",
    label: "Syringe",
    keywords: ["health", "hospital", "drugs", "blood", "medicine"],
  },
  {
    id: "pill",
    char: "💊",
    label: "Pill",
    keywords: ["health", "medicine", "doctor", "pharmacy", "drug"],
  },
  {
    id: "adhesive-bandage",
    char: "🩹",
    label: "Adhesive Bandage",
    keywords: ["heal", "aid", "band", "doctor", "medicine"],
  },
  {
    id: "door",
    char: "🚪",
    label: "Door",
    keywords: ["house", "entry", "exit", "doorway", "front"],
  },
  {
    id: "bed",
    char: "🛏️",
    label: "Bed",
    keywords: ["sleep", "rest", "bedroom", "hotel"],
  },
  {
    id: "couch-and-lamp",
    char: "🛋️",
    label: "Couch And Lamp",
    keywords: ["read", "chill", "hotel", "lounge", "settee"],
  },
  {
    id: "toilet",
    char: "🚽",
    label: "Toilet",
    keywords: ["restroom", "wc", "washroom", "bathroom", "potty"],
  },
  {
    id: "shower",
    char: "🚿",
    label: "Shower",
    keywords: ["clean", "water", "bathroom", "bath", "head"],
  },
  {
    id: "bathtub",
    char: "🛁",
    label: "Bathtub",
    keywords: ["clean", "shower", "bathroom", "bath", "bubble"],
  },
  {
    id: "soap",
    char: "🧼",
    label: "Soap",
    keywords: ["bar", "bathing", "cleaning", "lather", "soapdish"],
  },
  {
    id: "toothbrush",
    char: "🪥",
    label: "Toothbrush",
    keywords: ["hygiene", "dental", "bathroom", "brush", "clean"],
  },
  {
    id: "broom",
    char: "🧹",
    label: "Broom",
    keywords: ["cleaning", "sweeping", "witch", "brush", "sweep"],
  },
  {
    id: "basket",
    char: "🧺",
    label: "Basket",
    keywords: ["laundry", "farming", "picnic"],
  },
  {
    id: "shopping-cart",
    char: "🛒",
    label: "Shopping Cart",
    keywords: ["trolley"],
  },
  {
    id: "locked",
    char: "🔒",
    label: "Locked",
    keywords: ["security", "password", "padlock", "closed", "lock"],
  },
  {
    id: "unlocked",
    char: "🔓",
    label: "Unlocked",
    keywords: ["privacy", "security", "lock", "open", "padlock"],
  },
  {
    id: "key",
    char: "🔑",
    label: "Key",
    keywords: ["lock", "door", "password", "gold"],
  },
  {
    id: "old-key",
    char: "🗝️",
    label: "Old Key",
    keywords: ["lock", "door", "password", "clue"],
  },
  {
    id: "pushpin",
    char: "📌",
    label: "Pushpin",
    keywords: ["stationery", "mark", "here", "location", "pin"],
  },
  {
    id: "paperclip",
    char: "📎",
    label: "Paperclip",
    keywords: ["documents", "stationery", "clippy"],
  },
  {
    id: "scissors",
    char: "✂️",
    label: "Scissors",
    keywords: ["stationery", "cut", "black", "cutting", "tool"],
  },
  {
    id: "triangular-ruler",
    char: "📐",
    label: "Triangular Ruler",
    keywords: ["stationery", "math", "architect", "sketch", "set"],
  },
  {
    id: "pencil",
    char: "✏️",
    label: "Pencil",
    keywords: ["stationery", "write", "paper", "writing", "school"],
  },
  {
    id: "fountain-pen",
    char: "🖋️",
    label: "Fountain Pen",
    keywords: ["stationery", "writing", "write", "communication", "left"],
  },
  {
    id: "briefcase",
    char: "💼",
    label: "Briefcase",
    keywords: ["business", "documents", "work", "law", "legal"],
  },
  {
    id: "calendar",
    char: "📅",
    label: "Calendar",
    keywords: ["schedule", "date", "day", "emoji", "july"],
  },
  {
    id: "clipboard",
    char: "📋",
    label: "Clipboard",
    keywords: ["stationery", "documents"],
  },
  {
    id: "bar-chart",
    char: "📊",
    label: "Bar Chart",
    keywords: ["graph", "presentation", "stats", "metrics"],
  },
  {
    id: "chart-increasing",
    char: "📈",
    label: "Chart Increasing",
    keywords: ["graph", "presentation", "stats", "recovery", "business"],
  },
  {
    id: "magnifying-glass-tilted-left",
    char: "🔍",
    label: "Magnifying Glass Tilted Left",
    keywords: ["search", "zoom", "find", "detective", "icon"],
  },
  {
    id: "alarm-clock",
    char: "⏰",
    label: "Alarm Clock",
    keywords: ["time", "wake", "morning"],
  },
  {
    id: "hourglass-not-done",
    char: "⏳",
    label: "Hourglass Not Done",
    keywords: ["oldschool", "time", "countdown", "flowing", "sand"],
  },
  // --- Symbols ---
  {
    id: "check-mark-button",
    char: "✅",
    label: "Check Mark Button",
    keywords: ["green-square", "ok", "agree", "vote", "election"],
  },
  {
    id: "check-mark",
    char: "✔️",
    label: "Check Mark",
    keywords: ["ok", "nike", "answer", "yes", "tick"],
  },
  {
    id: "cross-mark",
    char: "❌",
    label: "Cross Mark",
    keywords: ["no", "delete", "remove", "cancel", "red"],
  },
  {
    id: "cross-mark-button",
    char: "❎",
    label: "Cross Mark Button",
    keywords: ["x", "green-square", "no", "deny", "negative"],
  },
  {
    id: "warning",
    char: "⚠️",
    label: "Warning",
    keywords: ["exclamation", "wip", "alert", "error", "problem"],
  },
  {
    id: "no-entry",
    char: "⛔",
    label: "No Entry",
    keywords: ["limit", "security", "privacy", "bad", "denied"],
  },
  {
    id: "prohibited",
    char: "🚫",
    label: "Prohibited",
    keywords: ["forbid", "stop", "limit", "denied", "disallow"],
  },
  {
    id: "question-mark",
    char: "❓",
    label: "Question Mark",
    keywords: ["doubt", "confused", "black", "ornament", "punctuation"],
  },
  {
    id: "exclamation-mark",
    char: "❗",
    label: "Exclamation Mark",
    keywords: [
      "heavy_exclamation_mark",
      "danger",
      "surprise",
      "punctuation",
      "wow",
    ],
  },
  {
    id: "double-exclamation-mark",
    char: "‼️",
    label: "Double Exclamation Mark",
    keywords: ["exclamation", "surprise", "bangbang", "punctuation", "red"],
  },
  {
    id: "exclamation-question-mark",
    char: "⁉️",
    label: "Exclamation Question Mark",
    keywords: ["wat", "punctuation", "surprise", "interrobang", "red"],
  },
  {
    id: "recycling-symbol",
    char: "♻️",
    label: "Recycling Symbol",
    keywords: ["arrow", "environment", "garbage", "trash", "black"],
  },
  {
    id: "infinity",
    char: "♾️",
    label: "Infinity",
    keywords: ["forever", "paper", "permanent", "sign", "unbounded"],
  },
  {
    id: "wavy-dash",
    char: "〰️",
    label: "Wavy Dash",
    keywords: ["draw", "line", "moustache", "mustache", "squiggle"],
  },
  {
    id: "sparkle",
    char: "❇️",
    label: "Sparkle",
    keywords: ["stars", "green-square", "awesome", "good", "fireworks"],
  },
  {
    id: "eight-pointed-star",
    char: "✴️",
    label: "Eight Pointed Star",
    keywords: ["orange-square", "shape", "polygon", "black", "orange"],
  },
  {
    id: "yin-yang",
    char: "☯️",
    label: "Yin Yang",
    keywords: ["balance", "religion", "tao", "taoist"],
  },
  {
    id: "peace-symbol",
    char: "☮️",
    label: "Peace Symbol",
    keywords: ["hippie", "sign"],
  },
  {
    id: "atom-symbol",
    char: "⚛️",
    label: "Atom Symbol",
    keywords: ["science", "physics", "chemistry", "atheist"],
  },
  {
    id: "om",
    char: "🕉️",
    label: "Om",
    keywords: ["hinduism", "buddhism", "sikhism", "jainism", "aumkara"],
  },
  {
    id: "star-of-david",
    char: "✡️",
    label: "Star Of David",
    keywords: ["judaism", "jew", "jewish", "magen", "religion"],
  },
  {
    id: "wheelchair-symbol",
    char: "♿",
    label: "Wheelchair Symbol",
    keywords: [
      "blue-square",
      "disabled",
      "accessibility",
      "access",
      "accessible",
    ],
  },
  {
    id: "no-smoking",
    char: "🚭",
    label: "No Smoking",
    keywords: ["cigarette", "blue-square", "smell", "smoke", "forbidden"],
  },
  {
    id: "no-one-under-eighteen",
    char: "🔞",
    label: "No One Under Eighteen",
    keywords: ["18", "drink", "pub", "night", "minor"],
  },
  {
    id: "up-arrow",
    char: "⬆️",
    label: "Up Arrow",
    keywords: ["blue-square", "continue", "top", "direction", "black"],
  },
  {
    id: "down-arrow",
    char: "⬇️",
    label: "Down Arrow",
    keywords: ["blue-square", "direction", "bottom", "black", "cardinal"],
  },
  {
    id: "left-arrow",
    char: "⬅️",
    label: "Left Arrow",
    keywords: ["blue-square", "previous", "back", "black", "cardinal"],
  },
  {
    id: "right-arrow",
    char: "➡️",
    label: "Right Arrow",
    keywords: ["blue-square", "next", "black", "cardinal", "direction"],
  },
  {
    id: "counterclockwise-arrows-button",
    char: "🔄",
    label: "Counterclockwise Arrows Button",
    keywords: ["blue-square", "sync", "cycle", "anticlockwise", "arrow"],
  },
  {
    id: "clockwise-vertical-arrows",
    char: "🔃",
    label: "Clockwise Vertical Arrows",
    keywords: ["sync", "cycle", "round", "repeat", "arrow"],
  },
  {
    id: "musical-note",
    char: "🎵",
    label: "Musical Note",
    keywords: ["score", "tone", "sound", "activity", "beamed"],
  },
  {
    id: "musical-notes",
    char: "🎶",
    label: "Musical Notes",
    keywords: ["music", "score", "activity", "entertainment", "multiple"],
  },
  {
    id: "plus-sign",
    char: "➕",
    label: "Plus Sign",
    keywords: ["math", "calculation", "addition", "more", "increase"],
  },
  {
    id: "minus-sign",
    char: "➖",
    label: "Minus Sign",
    keywords: ["math", "calculation", "subtract", "less", "heavy"],
  },
  {
    id: "multiplication-sign",
    char: "✖️",
    label: "Multiplication Sign",
    keywords: ["math", "calculation", "cancel", "heavy", "multiply"],
  },
  {
    id: "division-sign",
    char: "➗",
    label: "Division Sign",
    keywords: ["divide", "math", "calculation", "heavy", "symbol"],
  },
  {
    id: "keycap-10",
    char: "🔟",
    label: "Keycap 10",
    keywords: ["numbers", "10", "blue-square", "ten", "number"],
  },
  {
    id: "input-latin-letters",
    char: "🔤",
    label: "Input Latin Letters",
    keywords: ["blue-square", "alphabet", "abc", "for", "symbol"],
  },
  {
    id: "red-circle",
    char: "🔴",
    label: "Red Circle",
    keywords: ["shape", "error", "danger", "geometric", "large"],
  },
  {
    id: "orange-circle",
    char: "🟠",
    label: "Orange Circle",
    keywords: ["round", "geometric", "large"],
  },
  {
    id: "yellow-circle",
    char: "🟡",
    label: "Yellow Circle",
    keywords: ["round", "geometric", "large"],
  },
  {
    id: "green-circle",
    char: "🟢",
    label: "Green Circle",
    keywords: ["round", "geometric", "large"],
  },
  {
    id: "blue-circle",
    char: "🔵",
    label: "Blue Circle",
    keywords: ["shape", "icon", "button", "geometric", "large"],
  },
  {
    id: "purple-circle",
    char: "🟣",
    label: "Purple Circle",
    keywords: ["round", "geometric", "large"],
  },
  {
    id: "white-circle",
    char: "⚪",
    label: "White Circle",
    keywords: ["shape", "round", "geometric", "medium"],
  },
  {
    id: "black-circle",
    char: "⚫",
    label: "Black Circle",
    keywords: ["shape", "button", "round", "geometric", "medium"],
  },
  {
    id: "red-square",
    char: "🟥",
    label: "Red Square",
    keywords: ["card", "geometric", "large"],
  },
  {
    id: "green-square",
    char: "🟩",
    label: "Green Square",
    keywords: ["geometric", "large"],
  },
  {
    id: "blue-square",
    char: "🟦",
    label: "Blue Square",
    keywords: ["geometric", "large"],
  },
  {
    id: "black-large-square",
    char: "⬛",
    label: "Black Large Square",
    keywords: ["shape", "icon", "button", "geometric"],
  },
  {
    id: "white-large-square",
    char: "⬜",
    label: "White Large Square",
    keywords: ["shape", "icon", "stone", "button", "geometric"],
  },
  {
    id: "speech-balloon",
    char: "💬",
    label: "Speech Balloon",
    keywords: ["bubble", "words", "message", "talk", "chatting"],
  },
  {
    id: "thought-balloon",
    char: "💭",
    label: "Thought Balloon",
    keywords: ["bubble", "cloud", "speech", "thinking", "dream"],
  },
];
